################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
DisplayDriver \
Drivers/STM32F3xx_HAL_Driver/Src \
FreeRTOS-Plus-CLI \
LVGL/src/core \
LVGL/src/display \
LVGL/src/draw/convert/helium \
LVGL/src/draw/convert \
LVGL/src/draw/convert/neon \
LVGL/src/draw/dma2d \
LVGL/src/draw/espressif/ppa \
LVGL/src/draw/eve \
LVGL/src/draw \
LVGL/src/draw/nema_gfx \
LVGL/src/draw/nxp/g2d \
LVGL/src/draw/nxp/pxp \
LVGL/src/draw/opengles \
LVGL/src/draw/renesas/dave2d \
LVGL/src/draw/sdl \
LVGL/src/draw/sw/blend/helium \
LVGL/src/draw/sw/blend \
LVGL/src/draw/sw/blend/neon \
LVGL/src/draw/sw \
LVGL/src/draw/vg_lite \
LVGL/src/drivers/display/drm \
LVGL/src/drivers/display/fb \
LVGL/src/drivers/display/ft81x \
LVGL/src/drivers/display/ili9341 \
LVGL/src/drivers/display/lcd \
LVGL/src/drivers/display/nxp_elcdif \
LVGL/src/drivers/display/renesas_glcdc \
LVGL/src/drivers/display/st7735 \
LVGL/src/drivers/display/st7789 \
LVGL/src/drivers/display/st7796 \
LVGL/src/drivers/display/st_ltdc \
LVGL/src/drivers/draw/eve \
LVGL/src/drivers/evdev \
LVGL/src/drivers/libinput \
LVGL/src/drivers/nuttx \
LVGL/src/drivers/opengles/assets \
LVGL/src/drivers/opengles/glad/src \
LVGL/src/drivers/opengles \
LVGL/src/drivers/opengles/opengl_shader \
LVGL/src/drivers/qnx \
LVGL/src/drivers/sdl \
LVGL/src/drivers/uefi \
LVGL/src/drivers/wayland \
LVGL/src/drivers/windows \
LVGL/src/drivers/x11 \
LVGL/src/font \
LVGL/src/indev \
LVGL/src/layouts/flex \
LVGL/src/layouts/grid \
LVGL/src/layouts \
LVGL/src/libs/FT800-FT813 \
LVGL/src/libs/barcode \
LVGL/src/libs/bin_decoder \
LVGL/src/libs/bmp \
LVGL/src/libs/expat \
LVGL/src/libs/ffmpeg \
LVGL/src/libs/freetype \
LVGL/src/libs/frogfs/src \
LVGL/src/libs/fsdrv \
LVGL/src/libs/gif/AnimatedGIF/src \
LVGL/src/libs/gif \
LVGL/src/libs/gltf/gltf_view/assets \
LVGL/src/libs/gltf/gltf_view/ibl \
LVGL/src/libs/gstreamer \
LVGL/src/libs/libjpeg_turbo \
LVGL/src/libs/libpng \
LVGL/src/libs/lodepng \
LVGL/src/libs/lz4 \
LVGL/src/libs/qrcode \
LVGL/src/libs/rle \
LVGL/src/libs/rlottie \
LVGL/src/libs/svg \
LVGL/src/libs/tiny_ttf \
LVGL/src/libs/tjpgd \
LVGL/src/libs/vg_lite_driver/VGLite \
LVGL/src/libs/vg_lite_driver/VGLiteKernel \
LVGL/src/libs/vg_lite_driver/lv_vg_lite_hal \
LVGL/src \
LVGL/src/misc/cache/class \
LVGL/src/misc/cache/instance \
LVGL/src/misc/cache \
LVGL/src/misc \
LVGL/src/osal \
LVGL/src/others/file_explorer \
LVGL/src/others/font_manager \
LVGL/src/others/fragment \
LVGL/src/others/gridnav \
LVGL/src/others/ime \
LVGL/src/others/imgfont \
LVGL/src/others/monkey \
LVGL/src/others/observer \
LVGL/src/others/snapshot \
LVGL/src/others/sysmon \
LVGL/src/others/test \
LVGL/src/others/translation \
LVGL/src/others/vg_lite_tvg \
LVGL/src/others/xml \
LVGL/src/others/xml/parsers \
LVGL/src/stdlib/builtin \
LVGL/src/stdlib/clib \
LVGL/src/stdlib \
LVGL/src/stdlib/micropython \
LVGL/src/stdlib/rtthread \
LVGL/src/stdlib/uefi \
LVGL/src/themes/default \
LVGL/src/themes \
LVGL/src/themes/mono \
LVGL/src/themes/simple \
LVGL/src/tick \
LVGL/src/widgets/3dtexture \
LVGL/src/widgets/animimage \
LVGL/src/widgets/arc \
LVGL/src/widgets/arclabel \
LVGL/src/widgets/bar \
LVGL/src/widgets/button \
LVGL/src/widgets/buttonmatrix \
LVGL/src/widgets/calendar \
LVGL/src/widgets/canvas \
LVGL/src/widgets/chart \
LVGL/src/widgets/checkbox \
LVGL/src/widgets/dropdown \
LVGL/src/widgets/image \
LVGL/src/widgets/imagebutton \
LVGL/src/widgets/keyboard \
LVGL/src/widgets/label \
LVGL/src/widgets/led \
LVGL/src/widgets/line \
LVGL/src/widgets/list \
LVGL/src/widgets/lottie \
LVGL/src/widgets/menu \
LVGL/src/widgets/msgbox \
LVGL/src/widgets/objx_templ \
LVGL/src/widgets/property \
LVGL/src/widgets/roller \
LVGL/src/widgets/scale \
LVGL/src/widgets/slider \
LVGL/src/widgets/span \
LVGL/src/widgets/spinbox \
LVGL/src/widgets/spinner \
LVGL/src/widgets/switch \
LVGL/src/widgets/table \
LVGL/src/widgets/tabview \
LVGL/src/widgets/textarea \
LVGL/src/widgets/tileview \
LVGL/src/widgets/win \
. \
portable/GCC/ARM_CM4F \
portable/MemMang \

